version: '0.1'

services:
  scraper_service:
    build:
      context: ./scraper_service
    ports:
      - "5000:5000"
    depends_on:
      - db_service

  db_service:
    build:
      context: ./db_service
    ports:
      - "5001:5001"
